### ISSUE TITLE
excel file not working

### ISSUE THREAD

**Issue by bhunt2** [jonathanristo/VMMM-self-assessment-tool#1]
Jonathan, thank you for supporting the cyber security community through all of your various efforts. I downloaded the self assessment tool excel file but am not able to open the file. It says the file is corrupted or has the wrong file extension. I have tried several things to see what it is the matter but nothing has fixed it.

**Comment by jonathanristo** [comment]
just did some testing and seems to work on my end.

I did just upload a xls, and two zip files with the xlsx and xls files compressed as well.   Let me know if things work for you now

**Comment by bhunt2** [comment]
Still having issues. The zip files don't even open. I get 'The compressed (zipped) folder ... is invalid' when I try to open either of them. The .xls file seems like it will open but it says that the format doesn't match the file extension, but I usually don't open files that give this error even if it is possible. Not sure what is going on but I have been working with excel files all day with no issues.

**Comment by jonathanristo** [comment]
i will try it on another system here once I get to it and see if it has issues..

**Comment by jonathanristo** [comment]
ok.. i have it working on mac and windows here... 3 different systems.   downloads of the XLSX and the zip file load up no problem...even tried it with my restrictive work system... opened up

are you able to try on another system to see if the download works there instead?   

otherwise, I am not sure next steps

**Comment by jonathanristo** [comment]
this link is to an egnyte system that SANS has that we use for the MGT516 class..  try it.. **link expires June 1st**

https://sansorg.egnyte.com/dl/PLYXCaq5t9

**Comment by bhunt2** [comment]
The file from the link worked just fine. Not sure why there were issues with the files from Git when I use Git all the time. I will try cloning the repo instead of just a direct download and see if that changes things.

**Comment by bhunt2** [comment]
well, before cloning it I tried using the Github Download Zip function and downloaded everything as a Zip file. This worked. I wonder why I was unable to open files downloaded directly from the docs directly but it worked fine when downloading everything as a Zip. I was always able to download and open the PDF just fine, too. Must have to do with the Git settings. I have never experienced that before though.
Thanks for helping.

**Comment by jonathanristo** [comment]
glad it is working.... and that you were able to get the file.
